# Generated by Django 5.1.2 on 2024-11-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestConnectApp', '0002_mesa_pedido_info_alter_pedido_fecha_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=models.CharField(default='libre', max_length=20),
        ),
        migrations.AddField(
            model_name='mesa',
            name='garzon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='hora_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
