# Generated by Django 5.1.2 on 2024-11-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestConnectApp', '0006_alter_pedido_usuario_alter_reserva_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(default='libre', editable=False, max_length=20),
        ),
    ]
