# Generated by Django 5.1.2 on 2024-11-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestConnectApp', '0007_alter_mesa_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='pedido_info',
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada')], default='libre', max_length=10),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero_mesa',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
