# Generated by Django 5.1.2 on 2024-11-22 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestConnectApp', '0008_remove_mesa_pedido_info_alter_mesa_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='inventario_col',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reporteventas',
            name='fecha_reporte',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reporteventas',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='RestConnectApp.pedido'),
        ),
        migrations.AlterField(
            model_name='reporteventas',
            name='productos_mas_vendidos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mesa_asignada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
