# Generated by Django 5.1.2 on 2024-11-24 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestConnectApp', '0009_remove_producto_stock_minimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='pedido_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesa_actual', to='RestConnectApp.pedido'),
        ),
    ]
