# Generated by Django 5.1.2 on 2024-11-24 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestConnectApp', '0010_mesa_pedido_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='total',
        ),
    ]
